# Generated by Django 4.0.4 on 2022-05-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_board_remove_task_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="snoozed_till",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
