# Generated by Django 4.0.4 on 2022-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_snoozed_till"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["priority", "-created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.PositiveIntegerField(
                default=1, help_text="Priority 1 is most important"
            ),
        ),
    ]
