# Generated by Django 4.0.4 on 2022-05-05 11:56

from itertools import groupby

from django.db import migrations


def create_priority_for_old(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    all_tasks = Task.objects.order_by("category_id", "-created_at")
    for category_id, tasks in groupby(all_tasks, lambda t: t.category_id):
        tasks = list(tasks)
        for i in range(len(tasks)):
            # start from 1
            tasks[i].priority = i + 1
    Task.objects.bulk_update(all_tasks, ["priority"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_options_task_priority"),
    ]

    operations = [
        migrations.RunPython(create_priority_for_old),
    ]
