# Generated by Django 4.0.4 on 2022-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="create_date",
            new_name="created_at",
        ),
    ]
